name: Oracle 19C Patching

on:
  push:
    branches:
      - master
    
jobs:
  run-playbooks:
    runs-on: self-hosted
  steps:
  - uses: actions/checkout@v2
  - name: Run Ansible Playbook
    run: ansible-playbook ../../patch.yml